QUALITYCHECK_MEAN = 1
QUALITYCHECK_STD = 2
QUALITYCHECK_SAT = 3
STAT_START = 100
STAT_MEAN = 100
ACC_SAT = 101

QUALITYERROR_LOW = -1
QUALITYERROR_HIGH = -2
NO_ERROR = 0

FILE_TYPE_HDF = 'FILE_TYPE_HDF'
FILE_TYPE_GE = 'FILE_TYPE_GE'

REPORT_NONE = 'REPORT_NONE'
REPORT_ERRORS = 'REPORT_ERRORS'
REPORT_FULL = 'REPORT_FULL'

mapper = {
    'QUALITYCHECK_MEAN' : 1,
    'QUALITYCHECK_STD' : 2,
    'QUALITYCHECK_SAT' : 3,
    'STAT_START' : 100,
    'STAT_MEAN' : 100,
    'ACC_SAT' : 101,

    'QUALITYERROR_LOW' : -1,
    'QUALITYERROR_HIGH' : -2,
    'NO_ERROR' : 0,
}

def shared(name):
    return mapper[name]
